# For more information: https://laravel.com/docs/sail
version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "${FORWARD_NGINX_PORT:-80}:80"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - '.:/var/www/html'
      - ./docker/config/nginx/site.conf:/etc/nginx/conf.d/default.conf
      # so we can cache our github tokens
      - '~/.composer/docker-cache/:/root/.composer:cached'
      - '~/.config/composer/:/root/.config/composer:cached'
      - vscode-extensions:/root/.vscode-server/extensions
    networks:
      - devtest-net
    links:
      - php
      - mailhog
    depends_on:
      - mysql
    restart: unless-stopped
  php:
    # image: php:fpm
    restart: unless-stopped
    build:
       context: ./docker/config/php/
       dockerfile: Dockerfile
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - devtest-net
    volumes:
      - .:/var/www/html
      - ./docker/config/php/php.ini:/usr/local/etc/php/php.ini
    links:
      - mysql
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - '${FORWARD_PHPMYADMIN_PORT:-8080}:80'
    environment:
      - PMA_HOST=mysql
    networks:
      - devtest-net
  mysql:
    restart: unless-stopped
    image: 'mysql/mysql-server:latest'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
    volumes:
      - 'devtest:/var/lib/mysql'
      # delegated'
      # /etc/mysql/conf.d for x64
      # for arm image
      # - './docker/config/mysql/my.cnf:/etc/my.cnf'
    networks:
      - devtest-net
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
      retries: 3
      timeout: 5s
  mailhog:
    restart: unless-stopped
    image: 'mailhog/mailhog:latest'
    ports:
      - '${FORWARD_MAILHOG_PORT:-1025}:1025'
      - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
    networks:
      - devtest-net
networks:
  devtest-net:
    driver: bridge
volumes:
  devtest:
    driver: local
  vscode-extensions:
    driver: local
